# Generated by Django 2.2.7 on 2019-12-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191218_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(),
        ),
    ]
